version: '3.4'

x-common-variables: &common-variables
  SERVICE_DISCOVERY_SERVER_ADDRESS: 192.168.0.12
  SERVICE_DISCOVERY_SERVER_PORT: 8500
  LOCAL_ADDRESS: 192.168.0.12
  ZIPKIN_ADDRESS: 192.168.0.12
  ZIPKIN_PORT: 9411

services:
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    network_mode: bridge
  consul-service:
    image: consul:latest
    container_name: consul-server
    command: "agent -server -ui -node=server -bootstrap-expect=1 -client=0.0.0.0 -bind=0.0.0.0"
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    network_mode: bridge
  configuration-service:
    image: tonsaito/mtc-configuration-service:latest
    environment:
      <<: *common-variables
      PORT: 8888
      CONFIGURATION_SERVICE_REPOSITORY: https://github.com/tonsaito/configuration-repo-default.git
    ports:
      - "8888:8888"
    network_mode: bridge
    depends_on:
      - consul-service
  gateway-service:
    image: tonsaito/mtc-gateway-service:latest
    environment:
      <<: *common-variables
      PORT: 9080
    ports:
      - "9080:9080"
    network_mode: bridge
    depends_on:
      - configuration-service
    links:
      - zipkin